[pytest]
markers =
    validate_csv: mark test as CSV validation
    unmarked: mark test as unmarked by user
    xfail: expected to fail
    skip: skip test
testpaths = tests/test_csv
python_files = test_*.py
addopts = --html=report.html --self-contained-html
# ReportPortal settings 
rp_endpoint = https://reportportal.epam.com
rp_api_key = new-key_rjNwe4d4QmOz4ma1byDAbGd5bJuqWUUFWH2uJrULQnPdg5snqwz2JDaE5zGDQ-aR
rp_project = kunal_majumdar_personal